FROM python:3.9-slim-buster

WORKDIR /app

COPY api.py .
COPY database.py .
COPY requirements.txt .

RUN pip3 install -r requirements.txt

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
