version: '3'
networks:
  my_network:
services:
  mqtt_broker:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - '1883:1883/tcp'
    restart: always
    volumes:
      - ./config:/config/
      - ./data:/data
      - ./log:/log
  mongo-db:
    image: mongo:latest
    container_name: mymongo
    ports:
      - '27018:27018'
    restart: always
    networks:
      - my_network      
  mqtt_subscriber:
    build:
      context: .
      dockerfile: Dockerfile_mqtt
    depends_on:
      - mqtt_broker
      - mongo-db
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - '8000:8000'
    environment:
      - MQTT_BROKER_HOST=mqtt-broker  
    depends_on:
      - mqtt_subscriber
    networks:
      - my_network  
